config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

  resources :recipes

  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


  def index

    if params[:category].blank?
      @recipes = Recipe.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @recipes = Recipe.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if
    @recipe.save
    redirect_to @recipe
    else
    render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to root_path
  end

private
  def recipe_params
    params.require(:recipe).permit(:title, :text, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a> <%= link_to "Home", recipes_index_path, class: 'navbar-brand' %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">

            <% Category.all.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, recipes_path(category: category.name), class: 'nav-link'%>
            </li>
            <% end %>

            </li>
          </ul>
        </div>
      </nav>




    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-6">

<%= simple_form_for @recipe do |f| %>

  <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"} %>
  <%= f.input :title , class: 'form-control' %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>List of recepies</h1>




<div class="container">
  <div class="row">
    <div class="col-xs-12">
<% @recipes.each do |recipe|%>
      <table class="table table-hover">
      <td><%= recipe.title %></td>
      <td><%= recipe.text %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      </table>
<% end %>



<%= link_to "New", new_recipe_path, class:'btn btn-primary btn-sm' %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @recipe.text %>
</p>